CREATE TABLE IF NOT EXISTS customer_designs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  garment_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(150) NOT NULL,
  fabric_source VARCHAR(20) NOT NULL DEFAULT 'own',
  fabric_detail VARCHAR(300) NULL,
  color VARCHAR(50) NULL,
  neck VARCHAR(50) NULL,
  sleeve VARCHAR(50) NULL,
  length_opt VARCHAR(50) NULL,
  fit VARCHAR(50) NULL,
  embroidery VARCHAR(300) NULL,
  occasion VARCHAR(80) NULL,
  style VARCHAR(80) NULL,
  footwear VARCHAR(150) NULL,
  accessories VARCHAR(300) NULL,
  hairstyle VARCHAR(150) NULL,
  grooming VARCHAR(150) NULL,
  season VARCHAR(40) NULL,
  location_context VARCHAR(150) NULL,
  background VARCHAR(150) NULL,
  lighting VARCHAR(100) NULL,
  extra_preferences VARCHAR(500) NULL,
  custom_notes TEXT NULL,
  ai_prompt TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_fabric_source CHECK (fabric_source IN ('own','shop')),
  CONSTRAINT fk_designs_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_designs_garment FOREIGN KEY (garment_id) REFERENCES garments (id) ON DELETE RESTRICT,
  INDEX idx_designs_customer (customer_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prompt_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  design_id BIGINT UNSIGNED NULL,
  inputs_snapshot JSON NOT NULL,
  prompt_text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_phistory_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_phistory_design FOREIGN KEY (design_id) REFERENCES customer_designs (id) ON DELETE SET NULL,
  INDEX idx_phistory_user (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
